wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1637697400
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.12.7
      8:
      - 5
